version: "3"

volumes:
  php_socket:
  data:
networks:
  web:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: ./docker/infra/php/Dockerfile
    volumes:
      - php_socket:/var/run/php-fpm
    networks:
      - web
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/infra/web/Dockerfile
    volumes:
      - php_socket:/var/run/php-fpm
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - web
  postgres:
      image: postgres:13
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: '${DB_PASSWORD}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_DB: '${DB_DATABASE}'
        TZ: 'Asia/Tokyo'
      volumes:
        - data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      networks:
        - web