name: Build Containers

on:
  push:
    branches:
      - feature/container-apps

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # リソースグループ名やロケーションは env で指定
    env:
      ResourceGroupName: ${{ vars.RESOUCE_GROUP_NAME}}
      ResourceGroupLocation: "japaneast"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: azcry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image for PHP
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/infra/php/Dockerfile
        push: true
        tags: azcry.azurecr.io/laravel-app:latest

    - name: Build and push Docker image for Nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/infra/web/Dockerfile
        push: true
        tags: azcry.azurecr.io/laravel-nginx:latest
    # ビルドする。ARM テンプレートのJSONファイルが生成される。
    - name: Azure Bicep Build
      run: |
        az bicep build --file azure/containerapps.bicep --outdir azure/
    # what-if コマンドで実際の環境と diff をプレビューする。
    - name: Preview Azure Bicep
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az deployment group what-if -f azure/containerapps.json -g ${{ env.ResourceGroupName }} --name ${{ env.ResourceGroupName }}    
    # Azure へ反映する。
    - name: Deploy Azure Bicep
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az deployment group create --mode Incremental -f azure/containerapps.json -g ${{ env.ResourceGroupName }} --name ${{ env.ResourceGroupName }}