name: Build Containers

on:
  push:
    branches:
      - feature/deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image for PHP
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/infra/php/Dockerfile
        push: true
        tags: your-azure-registry-name/php:latest

    - name: Build and push Docker image for Nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/infra/web/Dockerfile
        push: true
        tags: your-azure-registry-name/nginx:latest

    # - name: Deploy to Azure Container Apps
    #   uses: azure/containerapps-deploy@v1
    #   with:
    #     app_name: your-app-name
    #     resource_group: your-resource-group
    #     registry_username: ${{ secrets.REGISTRY_USERNAME }}
    #     registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    #     image: your-azure-registry-name/php:latest
